version: '3.4'

services:
  catalogdb:
    image: mongo

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4
 
  portainer:
    image: dpage/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes: 
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:  
